# NUMPY
# ZEROS, ONES
# ARANGE
# EMPTY
# IDENTITY
# LINESPACE
# AXIS=0,AXIS=1
# SUM FUNCTION WITH AXIS
# TRANSPOSE MATRIX
# MIN & MAX IN ARRAY --> ARGMAX,ARGMIN,ARGSORT,(WITH AXIS ALSO)
# MATRIX OPERATION
# NP.SQRT,SUM,MAX,MIN
# FINDING THE DATA USING WHERE


In [ ]:
import numpy as np


In [17]:
arr=np.array([2,3,4])

In [18]:
arr

array([2, 3, 4])

# 1-D

In [23]:
arr=np.array([1,])
print(arr)
print(type(arr))
print(arr.ndim)

[1]
<class 'numpy.ndarray'>
1


# 2-D

In [26]:
arr2=np.array([[2,3,4],[4,5,6]])
print(arr2)
print(type(arr2))
print(arr2.ndim)

[[2 3 4]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [27]:
arr2=np.array([[2,3,4],[4,5,6,7]])
print(arr2)
print(type(arr2))
print(arr2.ndim)

[list([2, 3, 4]) list([4, 5, 6, 7])]
<class 'numpy.ndarray'>
1


<ipython-input-27-f6cc066791af>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2=np.array([[2,3,4],[4,5,6,7]])


# 3-D

In [30]:
x= np.array([[[2,3,4],[4,5,6],[6,7,8]]])
print(x)
print(type(x))
print(x.ndim)

[[[2 3 4]
  [4 5 6]
  [6 7 8]]]
<class 'numpy.ndarray'>
3


In [34]:
Q=np.array([[[3,4,5]]])
print(Q)
print(type(Q))
print(Q.ndim)

[[[3 4 5]]]
<class 'numpy.ndarray'>
3


# Zeros

In [35]:
print(np.zeros(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
print(np.zeros((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
print(np.zeros((2,4,5)))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


# ONES

In [39]:
print(np.ones(2))

[1. 1.]


In [40]:
print(np.ones((2,5,6)))

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [41]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Indetity

In [42]:
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


In [43]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# ARANGE

In [44]:
print(np.arange(4))

[0 1 2 3]


In [45]:
print(np.arange(4,10))

[4 5 6 7 8 9]


In [46]:
print(np.arange(4,10,2))

[4 6 8]


In [48]:
print(np.arange(10,4,-2))

[10  8  6]


In [49]:
print(np.arange(10,4))

[]


In [50]:
print(np.arange(10,4,2))

[]


# EMPTY

In [51]:
print(np.empty(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
print(np.empty((5,2)))

[[8.43965981e-312 2.07507571e-322]
 [0.00000000e+000 0.00000000e+000]
 [1.44635573e-307 1.16095484e-028]
 [1.07441485e+160 8.93176403e+271]
 [4.98131536e+151 9.69385786e-067]]


# LINSPACE

In [53]:
print(np.linspace(2,6,7))

[2.         2.66666667 3.33333333 4.         4.66666667 5.33333333
 6.        ]


# AXIS

In [54]:
w= np.array([[[3,4,5],[5,6,7],[7,8,9]]])
print(w)

[[[3 4 5]
  [5 6 7]
  [7 8 9]]]


In [55]:
w.sum

<function ndarray.sum>

In [56]:
w.sum()

54

In [57]:
w.sum(axis=0)

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [58]:
w.sum(axis=1)

array([[15, 18, 21]])

# Transpose

In [61]:
w.T

array([[[3],
        [5],
        [7]],

       [[4],
        [6],
        [8]],

       [[5],
        [7],
        [9]]])